### ISSUE TITLE
[Feature request] The trigger Statechange would include the changed state as a tag

### ISSUE THREAD

**Issue by bm480** [eriks5/org.scheffers.homey.sets#6]
In order to implement LED-Ring notifications based on the states in a set it would be easier if you know which state has actually triggered the Statechange (in dutch: Toestandswijziging). I'm currently struggling with states that have the same priority (eg. Wasmachine klaar/Wasdroger klaar). I find it difficult to act on the latest state change, knowing the state is a missing piece in the conditions required to make this work.

**Comment by eriks5** [comment]
It's not possible to add a tag to the 'state changed' trigger, since this is only triggered once for an action, but multiple states can change on a single action, eg. the 'clear all' and 'set all' actions will often change multiple states at once.

Triggering the 'state changed' trigger multiple times, once for each changed state, would cause all flows triggering on 'state changed' to trigger multiple times, which is inefficient, and could cause strange behaviour as it's not what you would expect.
