### ISSUE TITLE
Temporarily activation on already active state has undesirable effect.

### ISSUE THREAD

**Issue by SixFive7** [eriks5/org.scheffers.homey.sets#9]
Hi,

I'm using the sets to activate lights whilst I'm walking around. When I enter a room it activates a state "room 3" in the set "rooms". But it also temporarily activates states "room 2" and "room 4" for 5 seconds.
The result is that I can walk around without having to wait for any Z-wave delays for lights to turn on. And if I stay put in a single room, neighboring rooms just light up for 5 seconds. Perfect.
Except... when I temporarily active a state that is already activated (e.g. somebody is in that room) I expected nothing to happen. What happens however, is that the timer still continues and disables the room lights 5 seconds later.
Can the temporary activate function be changed so that temporarily activating an already activated state doesn't disable it after the timeout? If I wanted that behaviour I could easily do that already with a delayed disable action. And the workaround to get the expected behaviour described above currently requires many condition checks and double the flows.

Awesome Homey app though. One of the more useful ones :-) Thnx!

Kind regards

**Comment by eriks5** [comment]
Changing the existing 'Activate state temporarily' action would break existing configurations that depend on the current implementation. I could add a new action for this. Most difficult part is finding a label for the action that is not confusing and still short..

**Comment by SixFive7** [comment]
Hmm, good point. How about a checkbox on the same card with a (longer) tooltip. This might allow you to extend the functionality per single card without making everything unclear or breaking existing configurations.
In the meantime I have taken a step back and rebuild everything the other way around. That seems to work alright.

**Comment by eriks5** [comment]
I'm not going to change this, because it's easily fixed by changing your sets. 

The idea of the app is that you have different sets for each activity, with states for each sensor. 

In your case you should have eg. a set `lights in room 4`, which has states `motion in room 2` and `motion in room 4`. If there is motion in the rooms, you set the corresponding states, each with their own timeouts. If there is any state active in a set, you turn on the lights, if there is no state active, you turn off the lights.

In general, you should not set the same state from different sensors
